menu/main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('save-cart/', views.save_cart, name='save_cart'),
    path('add_product/', views.add_product, name='add_product'),
    path('add_admin/', views.add_admin, name='add_admin'),
    path('view_purchases/', views.view_purchases, name='view_purchases'),
    path('save_purchase/', views.save_purchase, name='save_purchase'),
    path('view_all_purchases/', views.view_all_purchases, name='view_all_purchases'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/menu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

menu/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    photo = models.ImageField(upload_to='product_photos/', blank=True, null=True)

    def __str__(self):
        return self.name

class Purchase(models.Model):
    nombre = models.CharField(max_length=255)
    email = models.EmailField()
    direccion = models.CharField(max_length=255, blank=True, null=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    created_at = models.DateTimeField(auto_now_add=True)
    purchase_data = models.JSONField()

    def __str__(self):
        return f'Compra de {self.nombre}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Primero guarda la instancia

        # Calcula el precio total después de que se guarde la instancia
        total_price = sum(item.product.price * item.quantity for item in self.items.all())
        self.total_price = total_price
        super().save(*args, **kwargs)  # Guarda nuevamente la instancia con el precio total actualizado

class PurchaseItem(models.Model):
    purchase = models.ForeignKey(Purchase, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} de {self.product.name}'

menu/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, Product

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price']  # Campos que deseas mostrar en el formulario

menu/main/views.py
from pyexpat.errors import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.template import loader, TemplateDoesNotExist
from .forms import CustomUserCreationForm, ProductForm
from .models import Product, Purchase, PurchaseItem
import json
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import logging


def home(request):
    products = Product.objects.all()
    return render(request, 'home.html', {'products': products})

@login_required
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('product_list')  # Redirige a donde sea necesario después de agregar el producto
    else:
        form = ProductForm()
    return render(request, 'add_product.html', {'form': form})

@login_required
def add_admin(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_staff = True
            user.save()
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'add_admin.html', {'form': form})

@login_required
def view_purchases(request):
    purchases = Purchase.objects.filter(user=request.user)
    return render(request, 'view_purchases.html', {'purchases': purchases})

@csrf_exempt
@require_POST
def save_cart(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        cart = data.get('cart', [])
        user = request.user

        try:
            # Crear una nueva compra
            purchase = Purchase.objects.create(nombre=user.username, email=user.email)

            for item in cart:
                product = Product.objects.get(id=item['id'])
                quantity = item['quantity']

                # Crear un nuevo ítem de compra
                PurchaseItem.objects.create(purchase=purchase, product=product, quantity=quantity)

            return JsonResponse({'success': True})

        except Exception as e:
            print(f"Error al guardar el carrito: {e}")
            return JsonResponse({'success': False, 'error': str(e)})

    return JsonResponse({'success': False, 'error': 'Método no permitido'}, status=400)

logger = logging.getLogger(__name__)

@csrf_exempt
@require_POST
def save_purchase(request):
    print("Vista save_purchase llamada")
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            nombre = data.get('nombre')
            email = data.get('email')
            direccion = data.get('direccion', None)
            items_data = data.get('purchase_data')  # Obtener directamente purchase_data sin decodificar

            if not (nombre and email and items_data):
                return JsonResponse({'success': False, 'error': 'Datos incompletos'})

            # Crear la compra y guardar purchase_data como JSON
            purchase = Purchase(nombre=nombre, email=email, direccion=direccion, purchase_data=json.dumps(items_data))
            purchase.save()

            total_price = 0

            for item_data in items_data:
                product_id = item_data['id']
                quantity = item_data['quantity']
                product = Product.objects.get(id=int(product_id))
                PurchaseItem.objects.create(purchase=purchase, product=product, quantity=quantity)
                total_price += product.price * quantity

            purchase.total_price = total_price
            purchase.save()

            messages.success(request, '¡Compra realizada exitosamente!')
            return JsonResponse({'success': True})

        except ValueError as ve:
            print(f"Error de decodificación JSON: {ve}")
            return JsonResponse({'success': False, 'error': 'Error en los datos JSON'})

        except Product.DoesNotExist as pde:
            return JsonResponse({'success': False, 'error': 'Uno o más productos no existen'})

        except Exception as e:
            print(f"Error al guardar la compra: {e}")
            return JsonResponse({'success': False, 'error': str(e)})

    return JsonResponse({'success': False, 'error': 'Método no permitido'}, status=400)

def view_all_purchases(request):
    purchases = Purchase.objects.all()
    products = Product.objects.all()  # Obtén todos los productos para mostrarlos en la lista

    if request.method == 'POST':
        # Procesar el formulario para agregar productos
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('view_all_purchases')  # Redirige a la misma página para actualizar la lista de compras
    else:
        form = ProductForm()

    return render(request, 'view_all_purchases.html', {'purchases': purchases, 'products': products, 'form': form})

def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        product.delete()
    return redirect('view_all_purchases')  # Redirige a la misma página para actualizar la lista de productos

menu/main/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carrito de Compras</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body>
    <div class="container">
        <h2>Menú</h2>
        <div class="row">
            {% for product in products %}
            <div class="col-md-3">
                <div class="card">
                    <img src="{% if product.photo %}/media/{{ product.photo }}{% else %}{% static 'images/default.jpg' %}{% endif %}" class="card-img-top" alt="{{ product.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">Precio: ${{ product.price }}</p>
                        <button class="btn btn-primary add-to-cart" data-id="{{ product.id }}" data-name="{{ product.name }}" data-price="{{ product.price }}">Agregar</button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <h3 class="mt-5">Carrito</h3>
        <ul id="cartDisplay" class="list-group"></ul>
        <div class="mt-3">
            <h4>Total: $<span id="totalPrice">0.00</span></h4>
        </div>

        <!-- Botón para abrir el modal -->
        <button type="button" class="btn btn-success mt-3" data-toggle="modal" data-target="#purchaseModal">
            Enviar Compra
        </button>

        <!-- Modal para datos de compra -->
        <div class="modal fade" id="purchaseModal" tabindex="-1" role="dialog" aria-labelledby="purchaseModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="purchaseModalLabel">Datos de Compra</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="purchaseForm" action="{% url 'save_purchase' %}" method="post">
                            {% csrf_token %}
                            <div id="productsContainer">
                                <!-- Aquí se añadirán dinámicamente los productos del carrito -->
                            </div>
                            <div class="form-group">
                                <label for="nombre">Nombre:</label>
                                <input type="text" class="form-control" id="nombre" name="nombre" required>
                            </div>
                            <div class="form-group">
                                <label for="email">Correo Electrónico:</label>
                                <input type="email" class="form-control" id="email" name="email" required>
                            </div>
                            <div class="form-group">
                                <label for="direccion">Dirección:</label>
                                <input type="text" class="form-control" id="direccion" name="direccion" required>
                            </div>
                            <input type="hidden" id="purchaseData" name="purchase_data" value="">
                            <!-- Agregar un campo oculto para enviar los datos del carrito -->
                        </form>                        
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="button" id="sendPurchaseButton" class="btn btn-primary">Enviar Compra</button>
                    </div>
                </div>
            </div>
        </div>

        <h3 class="mt-5">Indicadores Económicos</h3>
        <div id="economicIndicatorsCarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" id="economicIndicators">
                <!-- Aquí se mostrarán los indicadores económicos -->
            </div>
            <a class="carousel-control-prev" href="#economicIndicatorsCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Anterior</span>
            </a>
            <a class="carousel-control-next" href="#economicIndicatorsCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Siguiente</span>
            </a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'main/js/script.js' %}"></script>
</body>
</html>

menu/main/templates/view_all_purchases.html
<!-- view_all_purchases.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Compras</title>
    <!-- Agregar Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Opcional: Agregar Bootstrap JavaScript (si se necesitan funcionalidades JS) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="container">
            <h1>Lista de Compras</h1>
        
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Nombre del Cliente</th>
                        <th>Email</th>
                        <th>Dirección</th>
                        <th>Productos Comprados</th>
                        <th>Precio Total</th>
                        <th>Fecha de Creación</th>
                    </tr>
                </thead>
                <tbody>
                    {% for purchase in purchases %}
                    <tr>
                        <td>{{ purchase.id }}</td>
                        <td>{{ purchase.nombre }}</td>
                        <td>{{ purchase.email }}</td>
                        <td>{{ purchase.direccion }}</td>
                        <td>
                            <ul>
                                {% for item in purchase.items.all %}
                                <li>{{ item.quantity }} de {{ item.product.name }} ({{ item.product.price }})</li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>{{ purchase.total_price }}</td>
                        <td>{{ purchase.created_at }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="7">No hay compras disponibles.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        <h1>Agregar Producto</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">Nombre del Producto:</label>
                    <input type="text" class="form-control" id="id_name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="id_price">Precio:</label>
                    <input type="number" class="form-control" id="id_price" name="price" step="0.01" required>
                </div>
                <div class="form-group">
                    <label for="id_photo">Foto:</label>
                    <input type="file" class="form-control-file" id="id_photo" name="photo" required>
                </div>
                <button type="submit" class="btn btn-primary">Agregar Producto</button>
            </form>
        </div>
        
        <!-- Lista de Productos -->
        <h2>Lista de Productos</h2>
        <ul class="list-group">
            {% for product in products %}
            <li class="list-group-item">
                {{ product.name }} - ${{ product.price }}
                <form method="POST" action="{% url 'delete_product' product.id %}" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-danger float-right">Eliminar</button>
                </form>
            </li>
            {% empty %}
            <li class="list-group-item">No hay productos disponibles.</li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>